import type { Area, Equipment, Job } from './types'
import { format, addDays, subDays } from 'date-fns'
import { uid, nowISO } from './utils'

const d = (offset: number) => format(addDays(new Date(), offset), 'yyyy-MM-dd')
const ago = (offset: number) => subDays(new Date(), offset).toISOString()

export const seedAreas: Area[] = [
  { id: 'a-orchard', name: 'Orchard', emoji: '🍎', color: '#c25a36', createdAt: nowISO() },
  { id: 'a-barn', name: 'Barn', emoji: '🛖', color: '#b06e1c', createdAt: nowISO() },
  { id: 'a-paddock', name: 'North Paddock', emoji: '🌾', color: '#cf8c22', createdAt: nowISO() },
  { id: 'a-veg', name: 'Veg Garden', emoji: '🥬', color: '#436343', createdAt: nowISO() },
  { id: 'a-house', name: 'Around the House', emoji: '🏡', color: '#345034', createdAt: nowISO() },
  { id: 'a-dam', name: 'Dam & Creek', emoji: '💧', color: '#0ea5e9', createdAt: nowISO() },
]

export const seedEquipment: Equipment[] = [
  {
    id: 'e-tractor',
    name: 'Kubota Tractor',
    type: 'Tractor',
    emoji: '🚜',
    notes: 'Diesel. Check hydraulic fluid each service.',
    lastServiced: format(subDays(new Date(), 80), 'yyyy-MM-dd'),
    serviceIntervalDays: 90,
    hours: 412,
    createdAt: nowISO(),
  },
  {
    id: 'e-mower',
    name: 'Ride-on Mower',
    type: 'Mower',
    emoji: '🌱',
    notes: 'Sharpen blades at start of mowing season.',
    lastServiced: format(subDays(new Date(), 200), 'yyyy-MM-dd'),
    serviceIntervalDays: 120,
    hours: 96,
    createdAt: nowISO(),
  },
  {
    id: 'e-chainsaw',
    name: 'Chainsaw',
    type: 'Power tool',
    emoji: '🪚',
    notes: '2-stroke mix 50:1. Spare chain in barn.',
    lastServiced: format(subDays(new Date(), 30), 'yyyy-MM-dd'),
    serviceIntervalDays: 60,
    createdAt: nowISO(),
  },
  {
    id: 'e-pump',
    name: 'Water Pump',
    type: 'Irrigation',
    emoji: '⚙️',
    lastServiced: format(subDays(new Date(), 150), 'yyyy-MM-dd'),
    serviceIntervalDays: 180,
    createdAt: nowISO(),
  },
]

const base = {
  checklist: [],
  photos: [],
  recurrence: { unit: 'none' as const, every: 1 },
  createdAt: nowISO(),
  updatedAt: nowISO(),
}

export const seedJobs: Job[] = [
  {
    ...base,
    id: uid(),
    title: 'Fix loose gate hinge at orchard',
    notes: 'Top hinge has dropped — gate scrapes the ground. Bring the cordless drill and longer coach screws.',
    category: 'repair',
    priority: 'high',
    status: 'todo',
    areaId: 'a-orchard',
    dueDate: d(-1),
    createdAt: ago(2),
  },
  {
    ...base,
    id: uid(),
    title: 'Service the Kubota tractor',
    notes: 'Oil + filter, grease nipples, check hydraulic fluid and coolant.',
    category: 'machinery',
    priority: 'high',
    status: 'todo',
    equipmentId: 'e-tractor',
    dueDate: d(2),
    estMinutes: 120,
    cost: 85,
    checklist: [
      { id: uid(), text: 'Drain & replace engine oil', done: false },
      { id: uid(), text: 'New oil filter', done: false },
      { id: uid(), text: 'Grease all nipples', done: false },
      { id: uid(), text: 'Check hydraulic fluid', done: false },
    ],
  },
  {
    ...base,
    id: uid(),
    title: 'Clear gutters before autumn rain',
    category: 'seasonal',
    priority: 'normal',
    status: 'todo',
    areaId: 'a-house',
    dueDate: d(0),
    recurrence: { unit: 'years', every: 1 },
  },
  {
    ...base,
    id: uid(),
    title: 'Re-tension the north fence line',
    notes: 'Two strands sagging near the corner post. Cattle leaning over.',
    category: 'fencing',
    priority: 'urgent',
    status: 'doing',
    areaId: 'a-paddock',
    dueDate: d(0),
  },
  {
    ...base,
    id: uid(),
    title: 'Mulch the veg beds',
    category: 'garden',
    priority: 'low',
    status: 'todo',
    areaId: 'a-veg',
    dueDate: d(5),
  },
  {
    ...base,
    id: uid(),
    title: 'Refill water troughs',
    category: 'animals',
    priority: 'normal',
    status: 'todo',
    areaId: 'a-paddock',
    dueDate: d(0),
    recurrence: { unit: 'days', every: 2 },
  },
  {
    ...base,
    id: uid(),
    title: 'Sharpen mower blades for the season',
    category: 'machinery',
    priority: 'normal',
    status: 'todo',
    equipmentId: 'e-mower',
    dueDate: d(9),
  },
  {
    ...base,
    id: uid(),
    title: 'Replace cracked barn window pane',
    category: 'building',
    priority: 'low',
    status: 'todo',
    areaId: 'a-barn',
    dueDate: d(14),
  },
  {
    ...base,
    id: uid(),
    title: 'Clean dam pump filter',
    category: 'water',
    priority: 'normal',
    status: 'todo',
    areaId: 'a-dam',
    equipmentId: 'e-pump',
    dueDate: d(3),
    recurrence: { unit: 'months', every: 1 },
  },
  {
    ...base,
    id: uid(),
    title: 'Prune the apple trees',
    notes: 'Winter prune — remove crossing branches and water shoots.',
    category: 'seasonal',
    priority: 'normal',
    status: 'done',
    areaId: 'a-orchard',
    dueDate: d(-3),
    completedAt: ago(3),
  },
  {
    ...base,
    id: uid(),
    title: 'Check chainsaw chain tension',
    category: 'machinery',
    priority: 'low',
    status: 'done',
    equipmentId: 'e-chainsaw',
    completedAt: ago(1),
  },
]
